export const LIST_USERS_RECS_REQUEST = 'LIST_USERS_RECS_REQUEST';
export const LIST_USERS_RECS_DATA = 'LIST_USERS_RECS_DATA';
export const LIST_USERS_RECS_ERROR = 'LIST_USERS_RECS_ERROR';

export const GET_USERS_PROFILE_DATA = 'GET_USERS_PROFILE_DATA';
export const GET_USERS_PROFILE_ERROR = 'GET_USERS_PROFILE_ERROR';

export const UNFOLLOW_FRIEND_SUCCESS = 'UNFOLLOW_FRIEND_SUCCESS';
export const UNFOLLOW_FRIEND_ERROR = 'UNFOLLOW_FRIEND_ERROR';

export const FOLLOW_FRIEND_SUCCESS = 'FOLLOW_FRIEND_SUCCESS';
export const FOLLOW_FRIEND_ERROR = 'FOLLOW_FRIEND_ERROR';
