export const LIST_CONTACTS_REQUEST = 'LIST_CONTACTS_REQUEST';
export const LIST_CONTACTS_DATA = 'LIST_CONTACTS_DATA';
export const LIST_CONTACTS_ERROR = 'LIST_CONTACTS_ERROR';

export const UNFOLLOW_FRIEND_SUCCESS = 'UNFOLLOW_FRIEND_SUCCESS';
export const UNFOLLOW_FRIEND_ERROR = 'UNFOLLOW_FRIEND_ERROR';
