export const LIST_MY_RECS_REQUEST = 'LIST_MY_RECS_REQUEST';
export const LIST_MY_RECS_DATA = 'LIST_MY_RECS_DATA';
export const LIST_MY_RECS_ERROR = 'LIST_MY_RECS_ERROR';

export const DELETE_MY_REC_SUCCESS = 'DELETE_MY_REC_SUCCESS';
export const DELETE_MY_REC_ERROR = 'DELETE_MY_REC_ERROR';
