export const LIST_RECS_SUGGESTIONS_REQUEST = 'LIST_RECS_SUGGESTIONS_REQUEST';
export const LIST_RECS_SUGGESTIONS_DATA = 'LIST_RECS_SUGGESTIONS_DATA';
export const LIST_RECS_SUGGESTIONS_ERROR = 'LIST_RECS_SUGGESTIONS_ERROR';

export const LIST_FRIENDS_SUGGESTIONS_REQUEST =
  'LIST_FRIENDS_SUGGESTIONS_REQUEST';
export const LIST_FRIENDS_SUGGESTIONS_DATA = 'LIST_FRIENDS_SUGGESTIONS_DATA';
export const LIST_FRIENDS_SUGGESTIONS_ERROR = 'LIST_FRIENDS_SUGGESTIONS_ERROR';

export const FOLLOW_FRIEND_SUCCESS = 'FOLLOW_FRIEND_SUCCESS';
export const FOLLOW_FRIEND_ERROR = 'FOLLOW_FRIEND_ERROR';

export const LIST_RECS_AUTO_SUGGESTIONS_DATA =
  'LIST_RECS_AUTO_SUGGESTIONS_DATA';
export const LIST_RECS_AUTO_SUGGESTIONS_ERROR =
  'LIST_RECS_AUTO_SUGGESTIONS_ERROR';
